[deps]
AdaptiveOpticsSim = "002fb5eb-ad68-44a0-adbe-b299bfc2febc"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
HdrHistogram = "d0b8ac25-3072-4075-acf5-4a93ba78f71f"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[sources]
AdaptiveOpticsSim = {path = "../.."}
HdrHistogram = {url = "https://github.com/DarrylGamroth/HdrHistogram.jl.git", rev = "cd42987e0739c06d29d20b4341f088b85e7a620c"}

[compat]
AdaptiveOpticsSim = "0.1"
BenchmarkTools = "1"
CUDA = "6"
HdrHistogram = "0.4"
KernelAbstractions = "0.9.42"
julia = "1.12"
