name = "AdaptiveOptics"
uuid = "002fb5eb-ad68-44a0-adbe-b299bfc2febc"
authors = ["AdaptiveOptics.jl Contributors"]
version = "0.1.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
