#
# Bounded single-writer plant-command admission
#
# This layer owns copied command payloads, accepted-sequence history, a
# fixed-capacity future calendar, application-ready claims, and terminal model
# dispositions. It deliberately does not mutate an optic, model command
# silence, compose plant event phases, or define a HIL port or transport.
#

@inline function _command_admission_error(stage::Symbol, reason::Symbol,
    message::AbstractString)
    throw(PlantCommandError(stage, reason, String(message)))
end

struct _PlantCommandCounterToken end
const _PLANT_COMMAND_COUNTER_TOKEN = _PlantCommandCounterToken()

@inline function _checked_positive_command_counter(value::Integer,
    reason::Symbol, label::AbstractString)
    value > 0 || _command_admission_error(:command, reason,
        "$label must be positive")
    value <= typemax(UInt64) || _command_admission_error(:command, reason,
        "$label exceeds UInt64 range")
    return UInt64(value)
end

@inline _checked_positive_command_counter(::Bool, reason::Symbol,
    label::AbstractString) = _command_admission_error(:command, reason,
    "$label must be a positive integer, not Bool")

"""Positive endpoint-local sequence carried by one plant command."""
struct PlantCommandSequence
    value::UInt64

    PlantCommandSequence(value::UInt64, ::_PlantCommandCounterToken) =
        new(value)
end

PlantCommandSequence(value::Integer) = PlantCommandSequence(
    _checked_positive_command_counter(value, :invalid_sequence,
        "plant-command sequence"),
    _PLANT_COMMAND_COUNTER_TOKEN,
)

PlantCommandSequence(value) = _command_admission_error(:command,
    :invalid_sequence,
    "plant-command sequence must be an Integer; got $(typeof(value))")

"""
Endpoint-local identity assigned to one presentation attempt.

Unlike `PlantCommandSequence`, this value is generated by the endpoint so two
presentations carrying the same command sequence still receive distinct
terminal-disposition credits.
"""
struct CommandPresentationID
    value::UInt64

    CommandPresentationID(value::UInt64, ::_PlantCommandCounterToken) =
        new(value)
end

CommandPresentationID(value::Integer) = CommandPresentationID(
    _checked_positive_command_counter(value, :invalid_presentation,
        "command presentation identity"),
    _PLANT_COMMAND_COUNTER_TOKEN,
)

CommandPresentationID(value) = _command_admission_error(:command,
    :invalid_presentation,
    "command presentation identity must be an Integer; got $(typeof(value))")

const _PlantCommandCounter = Union{
    PlantCommandSequence,
    CommandPresentationID,
}

Base.:(==)(left::T, right::T) where {T<:_PlantCommandCounter} =
    left.value == right.value
Base.isequal(left::T, right::T) where {T<:_PlantCommandCounter} =
    isequal(left.value, right.value)
Base.hash(value::T, seed::UInt) where {T<:_PlantCommandCounter} =
    hash(value.value, hash(T, seed))

function Base.show(io::IO, value::_PlantCommandCounter)
    print(io, nameof(typeof(value)), "(", value.value, ")")
end

const _EMPTY_COMMAND_DISPOSITION_REASON = Symbol("")

"""Extensible, stable semantic reason attached to a terminal disposition."""
struct CommandDispositionReason
    name::Symbol

    function CommandDispositionReason(name::Symbol)
        name === _EMPTY_COMMAND_DISPOSITION_REASON &&
            _command_admission_error(:disposition,
                :empty_reason,
                "command disposition reason must not be empty")
        return new(name)
    end
end

CommandDispositionReason(value) = _command_admission_error(:disposition,
    :invalid_reason,
    "command disposition reason must be a Symbol; got $(typeof(value))")

Base.:(==)(left::CommandDispositionReason,
    right::CommandDispositionReason) = left.name == right.name
Base.isequal(left::CommandDispositionReason,
    right::CommandDispositionReason) = isequal(left.name, right.name)
Base.hash(value::CommandDispositionReason, seed::UInt) =
    hash(value.name, hash(CommandDispositionReason, seed))

function Base.show(io::IO, value::CommandDispositionReason)
    print(io, "CommandDispositionReason(", repr(value.name), ")")
end

@inline _as_plant_command_sequence(value::PlantCommandSequence) = value
@inline _as_plant_command_sequence(value::Integer) =
    PlantCommandSequence(value)

function _as_plant_command_sequence(value)
    _command_admission_error(:command, :invalid_sequence,
        "plant-command sequence must be an Integer or " *
        "PlantCommandSequence; got $(typeof(value))")
end

@inline _as_command_disposition_reason(value::CommandDispositionReason) =
    value
@inline _as_command_disposition_reason(value::Symbol) =
    CommandDispositionReason(value)

function _as_command_disposition_reason(value)
    _command_admission_error(:disposition, :invalid_reason,
        "command disposition reason must be a Symbol or " *
        "CommandDispositionReason; got $(typeof(value))")
end

"""
    PlantCommand(schema, sequence, effective_timestamp, payload)
    PlantCommand(endpoint, schema_id, schema_version, sequence,
        effective_timestamp, payload)

Immutable core command presented to one prepared endpoint. The payload remains
caller-owned only until admission returns; successful admission copies it into
endpoint-owned storage. Run/session correlation, external timestamps, leases,
and transports are deliberately absent.
"""
struct PlantCommand{P}
    endpoint::CommandEndpointID
    schema_id::PlantCommandSchemaID
    schema_version::PlantCommandSchemaVersion
    sequence::PlantCommandSequence
    effective_timestamp::PlantTimestamp
    payload::P
end

function PlantCommand(endpoint, schema_id, schema_version, sequence,
    effective_timestamp::PlantTimestamp, payload)
    return PlantCommand(
        _as_schema_command_endpoint_id(endpoint),
        _as_plant_command_schema_id(schema_id),
        _as_command_schema_version(schema_version),
        _as_plant_command_sequence(sequence),
        effective_timestamp,
        payload,
    )
end

function PlantCommand(schema::PlantCommandSchema, sequence,
    effective_timestamp::PlantTimestamp, payload)
    return PlantCommand(command_endpoint_id(schema), command_schema_id(schema),
        command_schema_version(schema), sequence, effective_timestamp,
        payload)
end

function PlantCommand(::PlantCommandSchema, sequence, effective_timestamp,
    payload)
    _command_admission_error(:command, :invalid_effective_timestamp,
        "plant-command effective timestamp must be a PlantTimestamp; got " *
        "$(typeof(effective_timestamp))")
end

function PlantCommand(endpoint, schema_id, schema_version, sequence,
    effective_timestamp, payload)
    _command_admission_error(:command, :invalid_effective_timestamp,
        "plant-command effective timestamp must be a PlantTimestamp; got " *
        "$(typeof(effective_timestamp))")
end

@inline command_endpoint_id(command::PlantCommand) = command.endpoint
@inline command_schema_id(command::PlantCommand) = command.schema_id
@inline command_schema_version(command::PlantCommand) = command.schema_version
@inline command_sequence(command::PlantCommand) = command.sequence
@inline command_effective_timestamp(command::PlantCommand) =
    command.effective_timestamp
@inline command_payload(command::PlantCommand) = command.payload

@enum CommandSequenceClass::UInt8 begin
    InOrderCommandSequence = 0x01
    DuplicateCommandSequence = 0x02
    StaleCommandSequence = 0x03
    ReorderedCommandSequence = 0x04
    SkippedCommandSequence = 0x05
end

@enum CommandAdmissionStatus::UInt8 begin
    CommandAdmittedPending = 0x01
    CommandAdmittedReady = 0x02
    CommandTerminatedOnAdmission = 0x03
end

@enum CommandTerminalKind::UInt8 begin
    RejectedCommand = 0x01
    SupersededCommand = 0x02
    AppliedCommand = 0x03
    FailedCommand = 0x04
end

"""
Total deterministic order key for application-ready plant commands.

Commands order by scheduled plant time, then endpoint-local command sequence,
then the stable prepared endpoint ordinal. A late apply-now command retains its
original requested timestamp separately and uses its admission time here.
"""
struct PlantCommandOrderKey
    timestamp::PlantTimestamp
    sequence::PlantCommandSequence
    endpoint_ordinal::UInt32
end

Base.:(==)(left::PlantCommandOrderKey, right::PlantCommandOrderKey) =
    left.timestamp == right.timestamp && left.sequence == right.sequence &&
    left.endpoint_ordinal == right.endpoint_ordinal
Base.isequal(left::PlantCommandOrderKey, right::PlantCommandOrderKey) =
    isequal(left.timestamp, right.timestamp) &&
    isequal(left.sequence, right.sequence) &&
    isequal(left.endpoint_ordinal, right.endpoint_ordinal)
Base.hash(key::PlantCommandOrderKey, seed::UInt) = hash(
    (key.timestamp, key.sequence, key.endpoint_ordinal), seed)

function Base.isless(left::PlantCommandOrderKey,
    right::PlantCommandOrderKey)
    left.timestamp == right.timestamp ||
        return left.timestamp < right.timestamp
    left.sequence == right.sequence ||
        return left.sequence.value < right.sequence.value
    return left.endpoint_ordinal < right.endpoint_ordinal
end

function Base.show(io::IO, key::PlantCommandOrderKey)
    print(io, "PlantCommandOrderKey(", repr(key.timestamp), ", ",
        repr(key.sequence), ", ", key.endpoint_ordinal, ")")
end

@inline command_effective_timestamp(key::PlantCommandOrderKey) = key.timestamp
@inline command_sequence(key::PlantCommandOrderKey) = key.sequence
@inline command_endpoint_ordinal(key::PlantCommandOrderKey) =
    key.endpoint_ordinal

"""Exactly one terminal core outcome for one command presentation."""
struct PlantCommandDisposition
    presentation_id::CommandPresentationID
    endpoint::CommandEndpointID
    sequence::PlantCommandSequence
    kind::CommandTerminalKind
    reason::CommandDispositionReason
    requested_effective_timestamp::PlantTimestamp
    terminal_timestamp::PlantTimestamp
    lateness::PlantDuration
    superseding_presentation::UInt64
end

@inline command_presentation_id(value::PlantCommandDisposition) =
    value.presentation_id
@inline command_endpoint_id(value::PlantCommandDisposition) = value.endpoint
@inline command_sequence(value::PlantCommandDisposition) = value.sequence
@inline command_terminal_kind(value::PlantCommandDisposition) = value.kind
@inline command_disposition_reason(value::PlantCommandDisposition) =
    value.reason
@inline command_requested_effective_timestamp(
    value::PlantCommandDisposition) = value.requested_effective_timestamp
@inline command_terminal_timestamp(value::PlantCommandDisposition) =
    value.terminal_timestamp
@inline command_lateness(value::PlantCommandDisposition) = value.lateness

@inline function superseding_command_presentation_id(
    value::PlantCommandDisposition)
    iszero(value.superseding_presentation) && return nothing
    return CommandPresentationID(value.superseding_presentation,
        _PLANT_COMMAND_COUNTER_TOKEN)
end

"""Immediate result of one nonthrowing plant-command admission decision."""
struct PlantCommandAdmission
    presentation_id::CommandPresentationID
    status::CommandAdmissionStatus
    sequence_class::Union{Nothing,CommandSequenceClass}
    order_key::Union{Nothing,PlantCommandOrderKey}
end

@inline command_presentation_id(value::PlantCommandAdmission) =
    value.presentation_id
@inline command_admission_status(value::PlantCommandAdmission) = value.status
@inline command_sequence_class(value::PlantCommandAdmission) =
    value.sequence_class
@inline command_order_key(value::PlantCommandAdmission) = value.order_key

mutable struct _CommandEndpointBinding end

"""
Run-immutable plan for one bounded command endpoint.

The plan binds one exact schema, positive calendar capacity, positive accepted-
sequence window, stable endpoint ordinal, and array backend. Mutable slot,
calendar, and sequence state live in `CommandEndpointState`.
"""
struct PreparedCommandEndpoint{S<:PlantCommandSchema,
    B<:AbstractArrayBackend}
    binding::_CommandEndpointBinding
    schema::S
    capacity::Int
    sequence_window::Int
    ordinal::UInt32
    backend::B
end

@inline command_schema(endpoint::PreparedCommandEndpoint) = endpoint.schema
@inline command_endpoint_id(endpoint::PreparedCommandEndpoint) =
    command_endpoint_id(endpoint.schema)
@inline command_endpoint_capacity(endpoint::PreparedCommandEndpoint) =
    endpoint.capacity
@inline command_sequence_window(endpoint::PreparedCommandEndpoint) =
    endpoint.sequence_window
@inline command_endpoint_ordinal(endpoint::PreparedCommandEndpoint) =
    endpoint.ordinal
@inline backend(endpoint::PreparedCommandEndpoint) = endpoint.backend
@inline _command_endpoint_binding_id(endpoint::PreparedCommandEndpoint) =
    UInt64(objectid(getfield(endpoint, :binding)))

@inline function _checked_command_endpoint_capacity(capacity::Integer)
    capacity > 0 || _command_admission_error(:preparation,
        :invalid_capacity, "command endpoint capacity must be positive")
    limit = min(typemax(UInt32), typemax(Int) - 1)
    capacity <= limit || _command_admission_error(:preparation,
        :invalid_capacity,
        "command endpoint capacity exceeds the supported slot range")
    return Int(capacity)
end

@inline _checked_command_endpoint_capacity(::Bool) =
    _command_admission_error(:preparation, :invalid_capacity,
        "command endpoint capacity must be an integer count, not Bool")

function _checked_command_endpoint_capacity(value)
    _command_admission_error(:preparation, :invalid_capacity,
        "command endpoint capacity must be an integer count; got " *
        "$(typeof(value))")
end

@inline function _checked_command_sequence_window(window::Integer)
    window > 0 || _command_admission_error(:preparation,
        :invalid_sequence_window,
        "command sequence window must be positive")
    window <= typemax(Int) || _command_admission_error(:preparation,
        :invalid_sequence_window,
        "command sequence window exceeds Int range")
    return Int(window)
end

@inline _checked_command_sequence_window(::Bool) =
    _command_admission_error(:preparation, :invalid_sequence_window,
        "command sequence window must be an integer count, not Bool")

function _checked_command_sequence_window(value)
    _command_admission_error(:preparation, :invalid_sequence_window,
        "command sequence window must be an integer count; got " *
        "$(typeof(value))")
end

@inline function _checked_command_endpoint_ordinal(ordinal::Integer)
    ordinal > 0 || _command_admission_error(:preparation,
        :invalid_ordinal, "command endpoint ordinal must be positive")
    ordinal <= typemax(UInt32) || _command_admission_error(:preparation,
        :invalid_ordinal,
        "command endpoint ordinal exceeds UInt32 range")
    return UInt32(ordinal)
end

@inline _checked_command_endpoint_ordinal(::Bool) =
    _command_admission_error(:preparation, :invalid_ordinal,
        "command endpoint ordinal must be an integer count, not Bool")

function _checked_command_endpoint_ordinal(value)
    _command_admission_error(:preparation, :invalid_ordinal,
        "command endpoint ordinal must be an integer count; got " *
        "$(typeof(value))")
end

@inline _validate_command_storage_backend(
    ::PlantCommandSchema{T,0}, ::AbstractArrayBackend) where {T} = nothing

function _validate_command_storage_backend(
    ::PlantCommandSchema{T,N}, backend::AbstractArrayBackend) where {T,N}
    resolve_array_backend(backend)
    return nothing
end

@inline function _validate_command_supersession_semantics(
    schema::PlantCommandSchema)
    policy = command_effective_time_policy(schema).supersession
    semantics = command_semantics(schema)
    policy == SupersedeOlderPendingCommands &&
        semantics == IncrementalCommand && _command_admission_error(
        :preparation,
        :invalid_incremental_supersession,
        "incremental command endpoints cannot discard older pending deltas; " *
        "use PreservePendingCommands or an absolute command schema",
    )
    return nothing
end

"""
    prepare_command_endpoint(schema; capacity, sequence_window=capacity,
        ordinal, backend=CPUBackend())

Prepare immutable bounds and storage policy for one command endpoint. Creating
its separate `CommandEndpointState` allocates exactly `capacity` active payload
slots plus one transactional staging slot for array payloads. No run-length-
sized storage, optic mutation, callback, clock, queue, or transport is added.
"""
function prepare_command_endpoint(schema::PlantCommandSchema;
    capacity,
    sequence_window=capacity,
    ordinal,
    backend::AbstractArrayBackend=CPUBackend())
    checked_capacity = _checked_command_endpoint_capacity(capacity)
    checked_window = _checked_command_sequence_window(sequence_window)
    checked_ordinal = _checked_command_endpoint_ordinal(ordinal)
    _validate_command_supersession_semantics(schema)
    _validate_command_storage_backend(schema, backend)
    return PreparedCommandEndpoint(_CommandEndpointBinding(), schema,
        checked_capacity, checked_window, checked_ordinal, backend)
end

abstract type _AbstractCommandPayloadSlots end

struct _ScalarCommandPayloadSlots{T} <: _AbstractCommandPayloadSlots
    values::Memory{T}
end

struct _ArrayCommandPayloadSlots{A<:AbstractArray} <:
    _AbstractCommandPayloadSlots
    values::Memory{A}
    staging_slot::Int
end

function _prepare_command_payload_slots(schema::PlantCommandSchema{T,0},
    ::AbstractArrayBackend, capacity::Int) where {T}
    return _ScalarCommandPayloadSlots(Memory{T}(undef, capacity))
end

function _prepare_command_payload_slots(schema::PlantCommandSchema{T,N},
    backend::AbstractArrayBackend, capacity::Int) where {T,N}
    count = capacity + 1
    first_slot = allocate_array(backend, T, schema.dimensions...)
    values = Memory{typeof(first_slot)}(undef, count)
    values[1] = first_slot
    @inbounds for index in 2:count
        values[index] = allocate_array(backend, T, schema.dimensions...)
    end
    return _ArrayCommandPayloadSlots(values, count)
end

@enum _CommandSlotStatus::UInt8 begin
    _FreeCommandSlot = 0x00
    _PendingCommandSlot = 0x01
    _ApplicationReadyCommandSlot = 0x02
end

struct _CommandSlotMetadata
    presentation::UInt64
    sequence::UInt64
    requested_effective_timestamp::PlantTimestamp
    scheduled_timestamp::PlantTimestamp
    admission_timestamp::PlantTimestamp
    generation::UInt64
    status::_CommandSlotStatus
end

@inline _empty_command_slot_metadata() = _CommandSlotMetadata(
    UInt64(0), UInt64(0), zero(PlantTimestamp), zero(PlantTimestamp),
    zero(PlantTimestamp), UInt64(0), _FreeCommandSlot)

"""Single-writer mutable storage for one prepared command endpoint."""
mutable struct CommandEndpointState{P<:_AbstractCommandPayloadSlots}
    binding::_CommandEndpointBinding
    payloads::P
    slots::Memory{_CommandSlotMetadata}
    calendar::Memory{UInt32}
    accepted_sequences::Memory{UInt64}
    pending_count::Int
    active_count::Int
    current_timestamp::PlantTimestamp
    highest_sequence::UInt64
    presentation_sequence::UInt64
    outstanding_slot::UInt32
    has_highest_sequence::Bool
end

function CommandEndpointState(endpoint::PreparedCommandEndpoint;
    initial_timestamp::PlantTimestamp=zero(PlantTimestamp))
    capacity = endpoint.capacity
    payloads = _prepare_command_payload_slots(endpoint.schema,
        endpoint.backend, capacity)
    slots = Memory{_CommandSlotMetadata}(undef, capacity)
    fill!(slots, _empty_command_slot_metadata())
    accepted_sequences = Memory{UInt64}(undef, endpoint.sequence_window)
    fill!(accepted_sequences, UInt64(0))
    return CommandEndpointState(
        getfield(endpoint, :binding),
        payloads,
        slots,
        Memory{UInt32}(undef, capacity),
        accepted_sequences,
        0,
        0,
        initial_timestamp,
        UInt64(0),
        UInt64(0),
        UInt32(0),
        false,
    )
end

"""
Caller-owned fixed storage for terminal dispositions produced by one endpoint
operation. The caller must inspect and explicitly clear all records before the
workspace can be reused; ordinary operations never overwrite unconsumed
credits.
"""
mutable struct CommandDispositionWorkspace
    binding::_CommandEndpointBinding
    dispositions::Memory{PlantCommandDisposition}
    count::Int
end

function CommandDispositionWorkspace(endpoint::PreparedCommandEndpoint)
    return CommandDispositionWorkspace(getfield(endpoint, :binding),
        Memory{PlantCommandDisposition}(undef, endpoint.capacity), 0)
end

@inline pending_command_count(state::CommandEndpointState) =
    state.pending_count
@inline active_command_count(state::CommandEndpointState) = state.active_count
@inline command_endpoint_timestamp(state::CommandEndpointState) =
    state.current_timestamp
@inline command_disposition_count(workspace::CommandDispositionWorkspace) =
    workspace.count

function command_disposition(workspace::CommandDispositionWorkspace,
    index::Integer)
    1 <= index <= workspace.count || _command_admission_error(:disposition,
        :invalid_index,
        "command disposition index must be within the current records")
    return workspace.dispositions[Int(index)]
end

@inline command_disposition(::CommandDispositionWorkspace, ::Bool) =
    _command_admission_error(:disposition, :invalid_index,
        "command disposition index must be an integer count, not Bool")

@inline command_disposition(::CommandDispositionWorkspace, index) =
    _command_admission_error(:disposition, :invalid_index,
        "command disposition index must be an integer count; got " *
        "$(typeof(index))")

function clear_command_dispositions!(workspace::CommandDispositionWorkspace)
    workspace.count = 0
    return workspace
end

@inline function _require_command_endpoint_binding(
    endpoint::PreparedCommandEndpoint, state::CommandEndpointState)
    getfield(endpoint, :binding) === state.binding ||
        _command_admission_error(:endpoint, :foreign_state,
            "command endpoint state belongs to another prepared endpoint")
    return nothing
end

@inline function _require_command_endpoint_binding(
    endpoint::PreparedCommandEndpoint,
    workspace::CommandDispositionWorkspace)
    getfield(endpoint, :binding) === workspace.binding ||
        _command_admission_error(:endpoint, :foreign_workspace,
            "command disposition workspace belongs to another prepared endpoint")
    return nothing
end

@inline function _require_empty_command_dispositions(
    workspace::CommandDispositionWorkspace)
    iszero(workspace.count) || _command_admission_error(:disposition,
        :unconsumed_dispositions,
        "clear the current command dispositions before reusing the workspace")
    return nothing
end

@inline function _require_idle_command_endpoint(state::CommandEndpointState)
    iszero(state.outstanding_slot) || _command_admission_error(:endpoint,
        :outstanding_application,
        "resolve the outstanding application-ready command before another " *
        "endpoint transition")
    return nothing
end

@inline function _require_forward_command_timestamp(
    state::CommandEndpointState, timestamp::PlantTimestamp)
    timestamp < state.current_timestamp && _command_admission_error(
        :endpoint, :time_regression,
        "command endpoint cannot move backward in plant time")
    return nothing
end

@inline function _next_command_counter(value::UInt64, reason::Symbol,
    label::AbstractString)
    value != typemax(UInt64) || _command_admission_error(:endpoint, reason,
        "$label exceeds UInt64 range")
    return value + UInt64(1)
end

@inline function _command_sequence_history_slot(sequence::UInt64,
    window::Int)
    return Int(mod(sequence - UInt64(1), UInt64(window))) + 1
end

function _classify_command_sequence(endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState, sequence::PlantCommandSequence)
    state.has_highest_sequence || return InOrderCommandSequence
    value = sequence.value
    slot = _command_sequence_history_slot(value, endpoint.sequence_window)
    state.accepted_sequences[slot] == value &&
        return DuplicateCommandSequence
    highest = state.highest_sequence
    if value > highest
        return value == highest + UInt64(1) ?
            InOrderCommandSequence : SkippedCommandSequence
    end
    highest - value >= UInt64(endpoint.sequence_window) &&
        return StaleCommandSequence
    return ReorderedCommandSequence
end

@inline function _record_accepted_command_sequence!(
    endpoint::PreparedCommandEndpoint, state::CommandEndpointState,
    sequence::PlantCommandSequence)
    value = sequence.value
    slot = _command_sequence_history_slot(value, endpoint.sequence_window)
    state.accepted_sequences[slot] = value
    if !state.has_highest_sequence || value > state.highest_sequence
        state.highest_sequence = value
        state.has_highest_sequence = true
    end
    return nothing
end

@inline function _command_sequence_action(policy::CommandSequencePolicy,
    sequence_class::CommandSequenceClass)
    sequence_class == InOrderCommandSequence && return AcceptSequence
    sequence_class == DuplicateCommandSequence && return policy.duplicate
    sequence_class == StaleCommandSequence && return policy.stale
    sequence_class == ReorderedCommandSequence && return policy.reordered
    return policy.skipped
end

@inline function _command_sequence_reason(
    sequence_class::CommandSequenceClass)
    sequence_class == DuplicateCommandSequence &&
        return CommandDispositionReason(:duplicate_sequence)
    sequence_class == StaleCommandSequence &&
        return CommandDispositionReason(:stale_sequence)
    sequence_class == ReorderedCommandSequence &&
        return CommandDispositionReason(:reordered_sequence)
    sequence_class == SkippedCommandSequence &&
        return CommandDispositionReason(:skipped_sequence)
    return CommandDispositionReason(:in_order_sequence)
end

"""
    validate_plant_command(endpoint, command)

Non-mutating validation of endpoint/schema identity and exact payload
compatibility. It does not assign a presentation credit, classify sequence,
admit, copy, schedule, supersede, claim, apply, or emit a disposition.
"""
function validate_plant_command(endpoint::PreparedCommandEndpoint,
    command::PlantCommand)
    command.endpoint == command_endpoint_id(endpoint) ||
        _command_admission_error(:validation, :endpoint_mismatch,
            "plant command targets $(command.endpoint); expected " *
            "$(command_endpoint_id(endpoint))")
    command.schema_id == command_schema_id(endpoint.schema) ||
        _command_admission_error(:validation, :schema_mismatch,
            "plant command schema $(command.schema_id) does not match " *
            "$(command_schema_id(endpoint.schema))")
    command.schema_version == command_schema_version(endpoint.schema) ||
        _command_admission_error(:validation, :schema_version_mismatch,
            "plant command schema version $(command.schema_version) does not " *
            "match $(command_schema_version(endpoint.schema))")
    validate_plant_command_payload(endpoint.schema, command.payload)
    return command
end

@inline function _command_lateness(timestamp::PlantTimestamp,
    requested::PlantTimestamp)
    requested < timestamp || return zero(PlantDuration)
    return timestamp - requested
end

@inline function _command_disposition(
    presentation_id::CommandPresentationID,
    endpoint::PreparedCommandEndpoint,
    sequence::PlantCommandSequence,
    kind::CommandTerminalKind,
    reason::CommandDispositionReason,
    requested_effective_timestamp::PlantTimestamp,
    terminal_timestamp::PlantTimestamp;
    superseding_presentation::UInt64=UInt64(0))
    return PlantCommandDisposition(
        presentation_id,
        command_endpoint_id(endpoint),
        sequence,
        kind,
        reason,
        requested_effective_timestamp,
        terminal_timestamp,
        _command_lateness(terminal_timestamp,
            requested_effective_timestamp),
        superseding_presentation,
    )
end

@inline function _next_command_presentation(state::CommandEndpointState)
    value = _next_command_counter(state.presentation_sequence,
        :presentation_overflow, "command presentation sequence")
    return CommandPresentationID(value, _PLANT_COMMAND_COUNTER_TOKEN)
end

@inline function _finish_terminal_admission!(
    workspace::CommandDispositionWorkspace,
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    command::PlantCommand,
    timestamp::PlantTimestamp,
    presentation_id::CommandPresentationID,
    kind::CommandTerminalKind,
    reason::CommandDispositionReason,
    sequence_class::Union{Nothing,CommandSequenceClass})
    disposition = _command_disposition(presentation_id, endpoint,
        command.sequence, kind, reason, command.effective_timestamp,
        timestamp)
    workspace.dispositions[1] = disposition
    workspace.count = 1
    state.presentation_sequence = presentation_id.value
    state.current_timestamp = timestamp
    return PlantCommandAdmission(presentation_id,
        CommandTerminatedOnAdmission, sequence_class, nothing)
end

@noinline function _finish_failed_admission!(
    workspace::CommandDispositionWorkspace,
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    command::PlantCommand,
    timestamp::PlantTimestamp,
    presentation_id::CommandPresentationID,
    reason::CommandDispositionReason,
    sequence_class::Union{Nothing,CommandSequenceClass},
    error_reason::Symbol,
    message::AbstractString)
    _finish_terminal_admission!(workspace, endpoint, state, command,
        timestamp, presentation_id, FailedCommand, reason, sequence_class)
    _command_admission_error(:admission, error_reason, message)
end

@inline function _validation_terminal_kind(error::PlantCommandError)
    error.reason === :nonfinite_failure && return FailedCommand
    error.reason === :out_of_range_failure && return FailedCommand
    return RejectedCommand
end

@noinline function _handle_command_validation_error!(
    workspace::CommandDispositionWorkspace,
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    command::PlantCommand,
    timestamp::PlantTimestamp,
    presentation_id::CommandPresentationID,
    error::PlantCommandError)
    kind = _validation_terminal_kind(error)
    reason = CommandDispositionReason(error.reason)
    if kind == FailedCommand
        return _finish_failed_admission!(workspace, endpoint, state, command,
            timestamp, presentation_id, reason, nothing, error.reason,
            error.msg)
    end
    return _finish_terminal_admission!(workspace, endpoint, state, command,
        timestamp, presentation_id, RejectedCommand, reason, nothing)
end

@noinline function _handle_command_validation_error!(
    workspace::CommandDispositionWorkspace,
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    command::PlantCommand,
    timestamp::PlantTimestamp,
    presentation_id::CommandPresentationID,
    error::InterruptException)
    throw(error)
end

@noinline function _handle_command_validation_error!(
    workspace::CommandDispositionWorkspace,
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    command::PlantCommand,
    timestamp::PlantTimestamp,
    presentation_id::CommandPresentationID,
    error)
    return _finish_failed_admission!(workspace, endpoint, state, command,
        timestamp, presentation_id,
        CommandDispositionReason(:payload_validation_failure), nothing,
        :payload_validation_failure,
        "plant-command payload validation failed unexpectedly " *
        "($(typeof(error)))")
end

@inline function _command_slot_key(endpoint::PreparedCommandEndpoint,
    metadata::_CommandSlotMetadata)
    return PlantCommandOrderKey(metadata.scheduled_timestamp,
        PlantCommandSequence(metadata.sequence, _PLANT_COMMAND_COUNTER_TOKEN),
        endpoint.ordinal)
end

function next_command_order_key(endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState)
    _require_command_endpoint_binding(endpoint, state)
    iszero(state.pending_count) && return nothing
    slot = Int(state.calendar[1])
    return _command_slot_key(endpoint, state.slots[slot])
end

@inline function _should_supersede_pending_command(
    endpoint::PreparedCommandEndpoint,
    metadata::_CommandSlotMetadata,
    sequence::PlantCommandSequence)
    policy = endpoint.schema.effective_time_policy.supersession
    policy == SupersedeOlderPendingCommands || return false
    return metadata.status == _PendingCommandSlot &&
        metadata.sequence < sequence.value
end

function _superseded_pending_commands(endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState, sequence::PlantCommandSequence)
    count = 0
    first_slot = UInt32(0)
    @inbounds for index in 1:state.pending_count
        slot = state.calendar[index]
        metadata = state.slots[Int(slot)]
        _should_supersede_pending_command(endpoint, metadata, sequence) ||
            continue
        count += 1
        iszero(first_slot) && (first_slot = slot)
    end
    return count, first_slot
end

function _find_free_command_slot(state::CommandEndpointState)
    @inbounds for index in eachindex(state.slots)
        state.slots[index].status == _FreeCommandSlot && return UInt32(index)
    end
    _command_admission_error(:endpoint, :storage_invariant,
        "command endpoint has no free payload slot despite available capacity")
end

@inline function _presentation_range_clipping(schema::PlantCommandSchema)
    policy = schema.value_policy
    return policy.range_stage == ValidateOnPresentation &&
        policy.out_of_range == ClipInvalidCommand
end

@inline function _stage_scalar_command_payload(payload,
    ::UnboundedCommandValues, ::Bool)
    return payload
end

@inline function _stage_scalar_command_payload(payload,
    bounds::UniformCommandBounds, clip_values::Bool)
    return clip_values ? clamp(payload, bounds.lower, bounds.upper) : payload
end

@inline function _stage_command_payload!(
    ::_ScalarCommandPayloadSlots,
    schema::PlantCommandSchema,
    payload)
    return _stage_scalar_command_payload(payload, schema.bounds,
        _presentation_range_clipping(schema))
end

function _stage_command_payload!(payloads::_ArrayCommandPayloadSlots,
    schema::PlantCommandSchema, payload::AbstractArray)
    staging = payloads.values[payloads.staging_slot]
    copyto!(staging, payload)
    _clip_staged_command_payload!(staging, schema.bounds,
        _presentation_range_clipping(schema))
    return nothing
end

@inline _clip_staged_command_payload!(::AbstractArray,
    ::UnboundedCommandValues, ::Bool) = nothing

@inline function _clip_staged_command_payload!(staging::AbstractArray,
    bounds::UniformCommandBounds, clip_values::Bool)
    clip_values && clamp_array!(staging, bounds.lower, bounds.upper)
    return nothing
end

@inline function _commit_staged_command_payload!(
    payloads::_ScalarCommandPayloadSlots, slot::Int, staged)
    payloads.values[slot] = staged
    return nothing
end

@inline function _commit_staged_command_payload!(
    payloads::_ArrayCommandPayloadSlots, slot::Int, ::Nothing)
    staging_slot = payloads.staging_slot
    destination = payloads.values[slot]
    payloads.values[slot] = payloads.values[staging_slot]
    payloads.values[staging_slot] = destination
    return nothing
end

@noinline function _handle_command_staging_error!(
    workspace::CommandDispositionWorkspace,
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    command::PlantCommand,
    timestamp::PlantTimestamp,
    presentation_id::CommandPresentationID,
    sequence_class::CommandSequenceClass,
    error::InterruptException)
    throw(error)
end

@noinline function _handle_command_staging_error!(
    workspace::CommandDispositionWorkspace,
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    command::PlantCommand,
    timestamp::PlantTimestamp,
    presentation_id::CommandPresentationID,
    sequence_class::CommandSequenceClass,
    error)
    return _finish_failed_admission!(workspace, endpoint, state, command,
        timestamp, presentation_id,
        CommandDispositionReason(:payload_storage_failure), sequence_class,
        :payload_storage_failure,
        "failed to copy the plant-command payload into endpoint-owned " *
        "storage ($(typeof(error)))")
end

function _write_superseded_dispositions!(
    workspace::CommandDispositionWorkspace,
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    sequence::PlantCommandSequence,
    timestamp::PlantTimestamp,
    superseding_presentation::CommandPresentationID)
    count = 0
    @inbounds for index in 1:state.pending_count
        slot = Int(state.calendar[index])
        metadata = state.slots[slot]
        _should_supersede_pending_command(endpoint, metadata, sequence) ||
            continue
        count += 1
        workspace.dispositions[count] = _command_disposition(
            CommandPresentationID(metadata.presentation,
                _PLANT_COMMAND_COUNTER_TOKEN),
            endpoint,
            PlantCommandSequence(metadata.sequence,
                _PLANT_COMMAND_COUNTER_TOKEN),
            SupersededCommand,
            CommandDispositionReason(:superseded_by_newer_sequence),
            metadata.requested_effective_timestamp,
            timestamp;
            superseding_presentation=superseding_presentation.value,
        )
    end
    return count
end

function _remove_superseded_pending_commands!(
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    sequence::PlantCommandSequence)
    write_index = 0
    removed = 0
    @inbounds for read_index in 1:state.pending_count
        slot = Int(state.calendar[read_index])
        metadata = state.slots[slot]
        if _should_supersede_pending_command(endpoint, metadata, sequence)
            state.slots[slot] = _CommandSlotMetadata(
                UInt64(0), UInt64(0), zero(PlantTimestamp),
                zero(PlantTimestamp), zero(PlantTimestamp),
                metadata.generation, _FreeCommandSlot)
            removed += 1
        else
            write_index += 1
            state.calendar[write_index] = UInt32(slot)
        end
    end
    state.pending_count = write_index
    state.active_count -= removed
    return removed
end

function _insert_pending_command_slot!(endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState, slot::UInt32)
    key = _command_slot_key(endpoint, state.slots[Int(slot)])
    insertion = state.pending_count + 1
    @inbounds while insertion > 1
        previous_slot = state.calendar[insertion - 1]
        previous_key = _command_slot_key(endpoint,
            state.slots[Int(previous_slot)])
        isless(key, previous_key) || break
        state.calendar[insertion] = previous_slot
        insertion -= 1
    end
    state.calendar[insertion] = slot
    state.pending_count += 1
    return key
end

@inline function _terminal_sequence_admission!(
    workspace::CommandDispositionWorkspace,
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    command::PlantCommand,
    timestamp::PlantTimestamp,
    presentation_id::CommandPresentationID,
    sequence_class::CommandSequenceClass,
    action::CommandSequenceAction)
    reason = _command_sequence_reason(sequence_class)
    if action == FailOnSequence
        return _finish_failed_admission!(workspace, endpoint, state, command,
            timestamp, presentation_id, reason, sequence_class,
            reason.name,
            "plant-command sequence policy requires structural failure")
    end
    return _finish_terminal_admission!(workspace, endpoint, state, command,
        timestamp, presentation_id, RejectedCommand, reason, sequence_class)
end

"""
    admit_plant_command!(workspace, endpoint, state, command, timestamp)

Validate and make one bounded single-writer admission decision at canonical
plant `timestamp`. Successful admission copies caller payload storage, records
the accepted sequence, and inserts one sorted pending slot. Ordinary rejection
returns `CommandTerminatedOnAdmission`; structural fail policies first publish
one `FailedCommand` disposition and then throw `PlantCommandError`.

Decision precedence is endpoint/schema/payload validation, sequence policy,
effective-time policy, supersession/capacity, and finally transactional payload
storage. A failure at an earlier stage never falls through to a later reason.

The first successfully admitted sequence establishes the endpoint baseline.
Only successful admissions enter the bounded accepted-sequence window. A
command rejected for time or capacity may therefore be retried with the same
endpoint sequence as a distinct presentation.
"""
function admit_plant_command!(workspace::CommandDispositionWorkspace,
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    command::PlantCommand,
    timestamp::PlantTimestamp)
    _require_command_endpoint_binding(endpoint, state)
    _require_command_endpoint_binding(endpoint, workspace)
    _require_empty_command_dispositions(workspace)
    _require_idle_command_endpoint(state)
    _require_forward_command_timestamp(state, timestamp)
    presentation_id = _next_command_presentation(state)

    try
        validate_plant_command(endpoint, command)
    catch error
        return _handle_command_validation_error!(workspace, endpoint, state,
            command, timestamp, presentation_id, error)
    end

    sequence_class = _classify_command_sequence(endpoint, state,
        command.sequence)
    sequence_action = _command_sequence_action(
        endpoint.schema.sequence_policy, sequence_class)
    sequence_action == AcceptSequence || return _terminal_sequence_admission!(
        workspace, endpoint, state, command, timestamp, presentation_id,
        sequence_class, sequence_action)

    requested = command.effective_timestamp
    scheduled = requested
    if timestamp < requested
        endpoint.schema.effective_time_policy.future == RejectFutureCommand &&
            return _finish_terminal_admission!(workspace, endpoint, state,
                command, timestamp, presentation_id, RejectedCommand,
                CommandDispositionReason(:future_command), sequence_class)
    elseif requested < timestamp
        late_policy = endpoint.schema.effective_time_policy.late
        if late_policy == RejectLateCommand
            return _finish_terminal_admission!(workspace, endpoint, state,
                command,
                timestamp, presentation_id, RejectedCommand,
                CommandDispositionReason(:late_command), sequence_class)
        elseif late_policy == FailOnLateCommand
            return _finish_failed_admission!(workspace, endpoint, state,
                command, timestamp, presentation_id,
                CommandDispositionReason(:late_command), sequence_class,
                :late_command,
                "late plant-command policy requires structural failure")
        end
        scheduled = timestamp
    end

    superseded_count, first_superseded_slot =
        _superseded_pending_commands(endpoint, state, command.sequence)
    resulting_active = state.active_count - superseded_count + 1
    if resulting_active > endpoint.capacity
        return _finish_terminal_admission!(workspace, endpoint, state, command,
            timestamp, presentation_id, RejectedCommand,
            CommandDispositionReason(:calendar_capacity), sequence_class)
    end

    slot = iszero(first_superseded_slot) ?
        _find_free_command_slot(state) : first_superseded_slot
    old_metadata = state.slots[Int(slot)]
    generation = _next_command_counter(old_metadata.generation,
        :slot_generation_overflow, "command payload-slot generation")

    staged = try
        _stage_command_payload!(state.payloads, endpoint.schema,
            command.payload)
    catch error
        return _handle_command_staging_error!(workspace, endpoint, state,
            command, timestamp, presentation_id, sequence_class, error)
    end

    disposition_count = _write_superseded_dispositions!(workspace, endpoint,
        state, command.sequence, timestamp, presentation_id)
    removed = _remove_superseded_pending_commands!(endpoint, state,
        command.sequence)
    removed == superseded_count || _command_admission_error(:endpoint,
        :storage_invariant,
        "command supersession preflight did not match calendar mutation")

    _commit_staged_command_payload!(state.payloads, Int(slot), staged)
    state.slots[Int(slot)] = _CommandSlotMetadata(
        presentation_id.value,
        command.sequence.value,
        requested,
        scheduled,
        timestamp,
        generation,
        _PendingCommandSlot,
    )
    key = _insert_pending_command_slot!(endpoint, state, slot)
    state.active_count += 1
    _record_accepted_command_sequence!(endpoint, state, command.sequence)
    state.presentation_sequence = presentation_id.value
    state.current_timestamp = timestamp
    workspace.count = disposition_count
    status = scheduled <= timestamp ?
        CommandAdmittedReady : CommandAdmittedPending
    return PlantCommandAdmission(presentation_id, status, sequence_class, key)
end

struct PlantCommandApplicationClaim
    binding_id::UInt64
    slot::UInt32
    generation::UInt64
    presentation_id::CommandPresentationID
    key::PlantCommandOrderKey
    requested_effective_timestamp::PlantTimestamp
    admission_timestamp::PlantTimestamp
    ready_timestamp::PlantTimestamp
end

@inline command_presentation_id(value::PlantCommandApplicationClaim) =
    value.presentation_id
@inline command_order_key(value::PlantCommandApplicationClaim) = value.key
@inline command_sequence(value::PlantCommandApplicationClaim) =
    value.key.sequence
@inline command_requested_effective_timestamp(
    value::PlantCommandApplicationClaim) = value.requested_effective_timestamp
@inline command_admission_timestamp(value::PlantCommandApplicationClaim) =
    value.admission_timestamp
@inline command_application_timestamp(value::PlantCommandApplicationClaim) =
    value.ready_timestamp
@inline command_lateness(value::PlantCommandApplicationClaim) =
    _command_lateness(value.ready_timestamp,
        value.requested_effective_timestamp)

"""
    claim_next_application_ready_command!(endpoint, state, timestamp)

Remove and claim the earliest pending command whose scheduled time is not
later than `timestamp`. At most one application claim may be outstanding. A
late drain records `timestamp` as the actual application-ready instant; it
never backdates plant state to the scheduled key.
"""
function claim_next_application_ready_command!(
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    timestamp::PlantTimestamp)
    _require_command_endpoint_binding(endpoint, state)
    _require_idle_command_endpoint(state)
    _require_forward_command_timestamp(state, timestamp)
    state.current_timestamp = timestamp
    iszero(state.pending_count) && return nothing

    slot = state.calendar[1]
    metadata = state.slots[Int(slot)]
    metadata.scheduled_timestamp <= timestamp || return nothing
    @inbounds for index in 2:state.pending_count
        state.calendar[index - 1] = state.calendar[index]
    end
    state.pending_count -= 1
    state.slots[Int(slot)] = _CommandSlotMetadata(
        metadata.presentation,
        metadata.sequence,
        metadata.requested_effective_timestamp,
        metadata.scheduled_timestamp,
        metadata.admission_timestamp,
        metadata.generation,
        _ApplicationReadyCommandSlot,
    )
    state.outstanding_slot = slot
    return PlantCommandApplicationClaim(
        _command_endpoint_binding_id(endpoint),
        slot,
        metadata.generation,
        CommandPresentationID(metadata.presentation,
            _PLANT_COMMAND_COUNTER_TOKEN),
        _command_slot_key(endpoint, metadata),
        metadata.requested_effective_timestamp,
        metadata.admission_timestamp,
        timestamp,
    )
end

@inline function _require_current_command_claim(
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    claim::PlantCommandApplicationClaim)
    _require_command_endpoint_binding(endpoint, state)
    _command_endpoint_binding_id(endpoint) == claim.binding_id ||
        _command_admission_error(:application, :foreign_claim,
            "application-ready command belongs to another endpoint")
    state.outstanding_slot == claim.slot || _command_admission_error(
        :application, :stale_claim,
        "application-ready command is stale or no longer outstanding")
    slot = Int(claim.slot)
    1 <= slot <= length(state.slots) || _command_admission_error(
        :application, :invalid_claim,
        "application-ready command contains an invalid payload slot")
    metadata = state.slots[slot]
    metadata.status == _ApplicationReadyCommandSlot &&
        metadata.generation == claim.generation &&
        metadata.presentation == claim.presentation_id.value ||
        _command_admission_error(:application, :stale_claim,
            "application-ready command no longer matches endpoint state")
    return slot, metadata
end

"""Borrow the endpoint-owned payload for the outstanding claim read-only."""
function claimed_command_payload(endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState, claim::PlantCommandApplicationClaim)
    slot, _ = _require_current_command_claim(endpoint, state, claim)
    return _claimed_command_payload(state.payloads, slot)
end

@inline _claimed_command_payload(payloads::_ScalarCommandPayloadSlots,
    slot::Int) = payloads.values[slot]
@inline _claimed_command_payload(payloads::_ArrayCommandPayloadSlots,
    slot::Int) = payloads.values[slot]

@inline function _release_claimed_command_slot!(state::CommandEndpointState,
    slot::Int, metadata::_CommandSlotMetadata)
    state.slots[slot] = _CommandSlotMetadata(
        UInt64(0), UInt64(0), zero(PlantTimestamp), zero(PlantTimestamp),
        zero(PlantTimestamp), metadata.generation, _FreeCommandSlot)
    state.active_count -= 1
    state.outstanding_slot = UInt32(0)
    return nothing
end

function _finish_command_application!(
    workspace::CommandDispositionWorkspace,
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    claim::PlantCommandApplicationClaim,
    kind::CommandTerminalKind,
    reason::CommandDispositionReason)
    _require_command_endpoint_binding(endpoint, workspace)
    _require_empty_command_dispositions(workspace)
    slot, metadata = _require_current_command_claim(endpoint, state, claim)
    disposition = _command_disposition(claim.presentation_id, endpoint,
        claim.key.sequence, kind, reason,
        metadata.requested_effective_timestamp, claim.ready_timestamp)
    workspace.dispositions[1] = disposition
    workspace.count = 1
    _release_claimed_command_slot!(state, slot, metadata)
    return disposition
end

"""
Record successful application after the caller has applied the borrowed
payload. This transition records the terminal credit and releases the slot; it
does not itself mutate an optic.
"""
function mark_plant_command_applied!(
    workspace::CommandDispositionWorkspace,
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    claim::PlantCommandApplicationClaim)
    return _finish_command_application!(workspace, endpoint, state, claim,
        AppliedCommand, CommandDispositionReason(:applied))
end

"""Record a declared application failure and release the claimed slot."""
function fail_plant_command_application!(
    workspace::CommandDispositionWorkspace,
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    claim::PlantCommandApplicationClaim;
    reason=CommandDispositionReason(:application_failure))
    resolved_reason = _as_command_disposition_reason(reason)
    return _finish_command_application!(workspace, endpoint, state, claim,
        FailedCommand, resolved_reason)
end

"""
    fail_pending_plant_commands!(workspace, endpoint, state, timestamp;
        reason=:endpoint_failure)

Boundedly terminate every pending command in calendar order. This is the core
failure/drain primitive for commands that have not become application-ready;
an outstanding application claim must be resolved separately.
"""
function fail_pending_plant_commands!(
    workspace::CommandDispositionWorkspace,
    endpoint::PreparedCommandEndpoint,
    state::CommandEndpointState,
    timestamp::PlantTimestamp;
    reason=CommandDispositionReason(:endpoint_failure))
    _require_command_endpoint_binding(endpoint, state)
    _require_command_endpoint_binding(endpoint, workspace)
    _require_empty_command_dispositions(workspace)
    _require_idle_command_endpoint(state)
    _require_forward_command_timestamp(state, timestamp)
    resolved_reason = _as_command_disposition_reason(reason)
    count = state.pending_count
    @inbounds for index in 1:count
        slot = Int(state.calendar[index])
        metadata = state.slots[slot]
        workspace.dispositions[index] = _command_disposition(
            CommandPresentationID(metadata.presentation,
                _PLANT_COMMAND_COUNTER_TOKEN),
            endpoint,
            PlantCommandSequence(metadata.sequence,
                _PLANT_COMMAND_COUNTER_TOKEN),
            FailedCommand,
            resolved_reason,
            metadata.requested_effective_timestamp,
            timestamp,
        )
        state.slots[slot] = _CommandSlotMetadata(
            UInt64(0), UInt64(0), zero(PlantTimestamp),
            zero(PlantTimestamp), zero(PlantTimestamp), metadata.generation,
            _FreeCommandSlot)
    end
    state.pending_count = 0
    state.active_count = 0
    state.current_timestamp = timestamp
    workspace.count = count
    return count
end
