export Detector
export LinearAPDDetector, SPADArrayDetector, MKIDArrayDetector
export NoiseModel, NoiseNone, NoisePhoton, NoiseReadout, NoisePhotonReadout
export AbstractSensor, CCDSensor, CMOSSensor, EMCCDSensor, InGaAsSensor
export HgCdTeSensor
export LinearEMMode, PhotonCountingEMMode, EMOutput, ConventionalOutput
export emccd_snr
export SequentialAcquisition, FrameTransferAcquisition
export HgCdTeAvalancheArraySensor
export SPADArraySensor, MKIDArraySensor, MKIDArrayCharacteristics
export SingleElementLinearAPD, LinearAPDChannelBank
export FrameResponseModel, NullFrameResponse, GaussianPixelResponse
export SampledFrameResponse, RectangularPixelAperture
export CMOSReadNoiseMap, InterpixelCapacitance, detector_mtf
export PixelResponseNonuniformity, DarkSignalNonuniformity, BadPixelMask
export CompositeDetectorDefectModel
export GlobalShutter, RollingShutter, RollingExposure, GlobalResetExposure
export SingleRead, AveragedNonDestructiveReads, CorrelatedDoubleSampling
export FowlerSampling, UpTheRampSampling, SkipperSampling
export FunctionFrameSource, InPlaceFrameSource
export FunctionExposureFrameSource, InPlaceExposureFrameSource
export FrameReadoutCorrectionModel, NullFrameReadoutCorrection
export ReferencePixelCommonModeCorrection, ReferenceRowCommonModeCorrection
export ReferenceColumnCommonModeCorrection, ReferenceOutputCommonModeCorrection
export CompositeFrameReadoutCorrection
export FrameReadoutProducts, NoFrameReadoutProducts
export MultiReadFrameReadoutProducts, UpTheRampReadoutProducts
export SkipperReadoutProducts, HgCdTeReadoutProducts
export SaturatingFrameNonlinearity, ExponentialPersistence
export AbstractDetectorThermalModel, NullDetectorThermalModel
export FixedTemperature, FirstOrderThermalModel
export ArrheniusRateLaw, LinearTemperatureLaw, ExponentialTemperatureLaw
export CountingDeadTimeModel, NoDeadTime, NonParalyzableDeadTime
export ParalyzableDeadTime, DutyCycleGate, FirstOrderAfterpulseMeanResponse
export NearestNeighborCountRedistribution, CompositeCountingMeanResponse
export capture!, output_frame, channel_output, detector_export_metadata
export prepare_detector_acquisition
export detector_ramp_slope, detector_ramp_intercept
export detector_ramp_cube, detector_ramp_times
export readout_ready, reset_integration!, thermal_model

public AbstractEMGainModel
public ClippedGaussianMultiplicationApproximation
public ConditionalGammaMultiplication
public AbstractHgCdTeAvalancheMultiplication
public ConditionalGammaAvalancheMultiplication
public ClippedGaussianAvalancheMultiplicationApproximation
public FrameWindow
public StaticCMOSOutputPattern
public HgCdTeReadout
public MKIDArrayExportMetadata
public detector_ramp_acquisition
public DetectorAcquisitionPlan, PreparedDetectorAcquisition
public detector_acquisition_detector, detector_acquisition_input
public detector_acquisition_plan, detector_acquisition_state
public detector_acquisition_workspace, detector_acquisition_products
