export CPUBackend, CUDABackend, AMDGPUBackend, MetalBackend
export AbstractArrayBackend, backend, compute_device

public AbstractComputeDevice, HostComputeDevice, AcceleratorComputeDevice
public compute_device_backend, compute_device_identifier
public AbstractComputeDeviceAvailability, ComputeDeviceAvailable
public ComputeDeviceUnavailable, ComputeDeviceError
public compute_device_availability, compute_device_is_available
public compute_device_unavailable_reason, allocate_array
