"""
    WavefrontSensors

Canonical owner of composed wavefront-sensor contracts, typed observations
and measurements, prepared stage protocols, and family-neutral execution
capabilities. Reusable physical WFS components remain owned by `Optics`, while
detector response and acquisition physics remain owned by `Detectors`.
"""
module WavefrontSensors

using KernelAbstractions
using Random

import ..AdaptiveOpticsSim:
    AdaptiveOpticsSimError,
    AbstractDetector,
    DimensionMismatchError,
    InvalidConfiguration,
    UnsupportedAlgorithm,
    bin2d!,
    center_resize2d!,
    geometric_slopes!,
    geometric_wavefront_slopes!

import ..Backends:
    AbstractArrayBackend,
    AbstractComputeDevice,
    AcceleratorStyle,
    CPUBackend,
    ExecutionStyle,
    HostComputeDevice,
    ScalarCPUStyle,
    _resolve_array_backend,
    _resolve_backend_selector,
    backend,
    backend_maximum_value,
    backend_sum_value,
    begin_kernel_phase,
    compute_device,
    execute_fft_plan!,
    execution_style,
    finish_kernel_phase!,
    launch_kernel!,
    launch_kernel_async!,
    packed_valid_pair_mean,
    plan_fft_backend!,
    plan_ifft_backend!,
    queue_kernel!,
    require_same_backend,
    synchronize_backend!

import ..Optics:
    AbstractCombinationPolicy,
    AbstractOpticalElement,
    AbstractOpticalNormalization,
    AbstractOpticalPlaneKind,
    AbstractOpticalProduct,
    AbstractPlaneCoordinateDomain,
    AbstractSource,
    AbstractSpatialMeasure,
    AbstractSpectralCoordinate,
    AchromaticSpectralCoordinate,
    AngularCoordinates,
    Asterism,
    CellIntegratedMeasure,
    CoherentFieldCombination,
    DetectorPlane,
    DimensionlessNormalization,
    ElectricField,
    ExtendedSource,
    IncoherentIntensityAddition,
    IntegratedSpectralChannel,
    IntensityMap,
    LGSProfileNaProfile,
    LGSProfileNone,
    LGSSource,
    MetricCoordinates,
    MicrolensArray,
    MonochromaticChannel,
    OpticalPlaneMetadata,
    OpticalProductBundle,
    PlaneAxisOrientation,
    PhotonRateNormalization,
    PointSampledMeasure,
    PreparedMicrolensPropagation,
    PupilFunction,
    PupilPlane,
    SpatialDensityMeasure,
    SpectralSample,
    SpectralSource,
    SubapertureGridMask,
    Telescope,
    _prepare_microlens_propagation,
    _pupil_diameter_m,
    _pupil_resolution,
    aperture_revision,
    axis_centering,
    build_mask!,
    centered_grid_origin,
    extended_source_asterism,
    fraunhofer_intensity_stack!,
    lgs_elongation_factor,
    lgs_profile,
    is_lgs_source,
    microlens_array,
    photon_irradiance,
    pupil_mask,
    pupil_reflectivity,
    require_leaf_source,
    reset_opd!,
    source_measurement_signature,
    source_with_wavelength_and_radiometric_value,
    spectral_bundle,
    validate_plane_storage,
    wavelength

import ..Detectors:
    AbstractChargeCouplingModel,
    AbstractCountingDetector,
    AbstractEMCCDOperatingMode,
    AbstractEMCCDOutputPath,
    AbstractFrameResponse,
    AbstractQuantumEfficiencyModel,
    AveragedNonDestructiveReads,
    BackgroundModel,
    BadPixelMask,
    CCDSensor,
    CMOSSensor,
    CompositeDetectorDefectModel,
    CompositeFrameReadoutCorrection,
    ConventionalOutput,
    CorrelatedDoubleSampling,
    DarkSignalNonuniformity,
    Detector,
    EMCCDSensor,
    FowlerSampling,
    FrameReadoutCorrectionModel,
    FrameSamplingMode,
    FrameSensorType,
    GaussianPixelResponse,
    HgCdTeAvalancheArraySensor,
    InGaAsSensor,
    LinearEMMode,
    MKIDArrayDetector,
    NoBackground,
    NullChargeCoupling,
    NullDetectorDefectModel,
    NullFrameReadoutCorrection,
    NullFrameResponse,
    PixelResponseNonuniformity,
    RectangularPixelAperture,
    ReferenceColumnCommonModeCorrection,
    ReferenceOutputCommonModeCorrection,
    ReferencePixelCommonModeCorrection,
    ReferenceRowCommonModeCorrection,
    SampledFrameResponse,
    SampledQuantumEfficiency,
    ScalarQuantumEfficiency,
    SingleRead,
    SkipperSampling,
    UpTheRampSampling,
    apply_readout_correction!,
    apply_response!,
    capture!,
    capture_stack!,
    capture_stack_with_quantum_efficiency!,
    capture_with_quantum_efficiency!,
    counting_array,
    counting_exposure_time,
    counting_fill_factor,
    counting_post_gain,
    counting_qe,
    counting_source_throughput,
    effective_qe,
    ensure_buffers!,
    detector_output_type,
    detector_output_value,
    output_frame,
    prepare_detector_acquisition,
    prepare_signal_frame!,
    qe_at,
    quantum_efficiency_model,
    is_null_cmos_output_model,
    is_null_frame_nonlinearity,
    is_null_persistence,
    persistence_model,
    require_whole_capture_idle,
    response_width_px,
    validate_frame_response_model,
    validate_up_the_ramp_schedule

include("abstract_wfs.jl")
include("sensing_modes.jl")
include("stage_contracts.jl")
include("grouped.jl")
include("interface.jl")
include("calibration.jl")
include("elongation.jl")
include("subapertures.jl")
include("shack_hartmann.jl")
include("api.jl")

end # module WavefrontSensors
