# Curated public API exported by `using AdaptiveOpticsSim`.
#
# Advanced and developer-facing names remain accessible as
# `AdaptiveOpticsSim.name`. Add names here only when they are part of ordinary
# user workflows, maintained examples, or stable extension seams.

export AdaptiveOpticsSimError, InvalidConfiguration, DimensionMismatchError
export UnsupportedAlgorithm, NumericalConditionError
export AtmosphereTimeError, AtmosphereEpochError
export WFSPreparationError

export FidelityProfile, ScientificProfile, FastProfile, default_fidelity_profile
export runtime_rng, deterministic_reference_rng

export InversePolicy, ExactPseudoInverse, TSVDInverse, TikhonovInverse, default_modal_inverse_policy
export CPUBackend, CUDABackend, AMDGPUBackend, MetalBackend
export AbstractArrayBackend, backend

export CircularAperture, AnnularAperture, SpiderMask, RectangularROI, SubapertureGridMask
export build_mask!, apply_mask!

export AbstractAtmosphere
export Telescope, Source, LGSSource, Asterism
export AbstractSourceRadiometry, PhysicalPhotonIrradianceSource
export NormalizedTestSource, source_radiometry, source_radiometric_value
export wavelength, photon_irradiance, optical_path, pupil_photon_rate_map
export reset_opd!, apply_opd!, set_pupil!, set_pupil_reflectivity!
export pupil_mask, pupil_reflectivity, apply_spiders!
export compute_psf!, psf_pixel_scale_arcsec

export SpectralSample, SpectralBundle, SpectralSource, with_spectrum
export GaussianDiskSourceModel, PointCloudSourceModel, SampledImageSourceModel
export with_extended_source, extended_source_asterism

export AbstractOpticalProduct, AbstractOpticalPlaneKind
export PupilPlane, FocalPlane, IntermediatePlane, DetectorPlane
export AbstractPlaneCoordinateDomain, MetricCoordinates, AngularCoordinates
export PlaneCentering, SampleCentered, InterSampleCentered
export PlaneAxisOrientation, UnspecifiedSpectralCoordinate
export AchromaticSpectralCoordinate, MonochromaticChannel
export IntegratedSpectralChannel
export AbstractOpticalNormalization, PhotonRateNormalization
export DimensionlessNormalization
export AbstractSpatialMeasure, PointSampledMeasure, SpatialDensityMeasure
export CellIntegratedMeasure
export AbstractCombinationPolicy, CoherentFieldCombination
export IncoherentIntensityAddition, NonCombinableProduct
export UnspecifiedNormalization, UnspecifiedSpatialMeasure, UnspecifiedCoherence
export OpticalPlaneMetadata, plane_metadata, plane_device
export PupilFunction, pupil_amplitude, opd_map
export surface_opd, update_surface!, apply_surface!
export ElectricField, field_values, IntensityMap, intensity_values
export OpticalProductBundle, PreparedIncoherentSum
export prepare_incoherent_sum, accumulate_intensity!
export PupilFieldFormationPlan, prepare_pupil_field
export fill_electric_field!, fill_electric_field_async!
export FraunhoferPropagation, FresnelPropagation
export propagation_output, propagate_field!, fraunhofer_intensity_from_field!
export DirectPSFPlan, DirectPSFWorkspace, prepare_direct_psf
export GeometricAtmosphericPropagation, LayeredFresnelAtmosphericPropagation
export AtmosphericFieldPropagation
export propagate_atmosphere_field!, atmospheric_intensity!

export ZernikeBasis, compute_zernike!
export OPDMap, Misregistration, apply_misregistration
export NCPA, KLBasis, ZernikeModalBasis
export SpatialFilter, SpatialFilterWorkspace, SpatialFilterPlan
export CircularFilter, SquareFilter, FoucaultFilter
export prepare_spatial_filter, filter!

export KolmogorovAtmosphere, MultiLayerAtmosphere, InfinitePhaseScreen, InfiniteMultiLayerAtmosphere
export AtmosphereEpoch, epoch_time, epoch_sequence, current_epoch
export prepare_atmosphere_renderer, prepare_atmosphere_renderers, direction_renderers
export advance!, advance_by!, advance_to!, propagate!
export render_atmosphere!

export ActuatorGridTopology, SampledActuatorTopology
export GaussianInfluenceWidth, GaussianMechanicalCoupling, DenseInfluenceMatrix, MeasuredInfluenceFunctions
export ClippedActuators, ActuatorHealthMap, CompositeDMActuatorModel
export DeformableMirror, apply!
export influence_model, influence_width
export mechanical_coupling, n_actuators
export FunctionModalBasis, MatrixModalBasis, ZernikeOpticBasis, CartesianTiltBasis
export CompositeControllableOptic, ModalControllableOptic, TipTiltMirror, FocusStage
export update_command!
export DMAdditive, DMReplace

export Detector, APDDetector, LinearAPDDetector, SPADArrayDetector, MKIDArrayDetector
export NoiseModel, NoiseNone, NoisePhoton, NoiseReadout, NoisePhotonReadout
export SensorType, CCDSensor, CMOSSensor, EMCCDSensor, InGaAsSensor
export LinearEMMode, PhotonCountingEMMode, EMOutput, ConventionalOutput, emccd_snr
export SequentialAcquisition, FrameTransferAcquisition
export HgCdTeAvalancheArraySensor, APDSensor, SPADArraySensor, MKIDArraySensor
export SingleElementAPD, APDChannelBank
export FrameResponseModel, NullFrameResponse, GaussianPixelResponse, SampledFrameResponse
export RectangularPixelAperture
export CMOSReadNoiseMap, InterpixelCapacitance, detector_mtf
export PixelResponseNonuniformity, DarkSignalNonuniformity, BadPixelMask, CompositeDetectorDefectModel
export GlobalShutter, RollingShutter, RollingExposure, GlobalResetExposure
export SingleRead, AveragedNonDestructiveReads, CorrelatedDoubleSampling, FowlerSampling
export UpTheRampSampling, SkipperSampling
export FunctionFrameSource, InPlaceFrameSource, FunctionExposureFrameSource, InPlaceExposureFrameSource
export FrameReadoutCorrectionModel, NullFrameReadoutCorrection
export ReferencePixelCommonModeCorrection, ReferenceRowCommonModeCorrection
export ReferenceColumnCommonModeCorrection, ReferenceOutputCommonModeCorrection
export CompositeFrameReadoutCorrection
export FrameReadoutProducts, NoFrameReadoutProducts, MultiReadFrameReadoutProducts
export UpTheRampReadoutProducts, SkipperReadoutProducts, HgCdTeReadoutProducts
export SaturatingFrameNonlinearity, ExponentialPersistence
export AbstractDetectorThermalModel, NullDetectorThermalModel, FixedTemperature, FirstOrderThermalModel
export ArrheniusRateLaw, LinearTemperatureLaw, ExponentialTemperatureLaw
export CountingDeadTimeModel, NoDeadTime, NonParalyzableDeadTime, ParalyzableDeadTime
export DutyCycleGate, AfterpulsingModel, ChannelCrosstalkModel, CompositeCountingCorrelation
export capture!, output_frame, channel_output, detector_export_metadata
export DetectorAcquisitionPlan, prepare_detector_acquisition
export detector_ramp_slope, detector_ramp_intercept
export detector_ramp_cube, detector_ramp_times
export readout_ready, reset_integration!, thermal_model

export Diffractive, Geometric
export WFSObservationMetadata, WFSMeasurementMetadata
export WFSObservation, WFSMeasurement
export observation_storage, observation_units, observation_metadata
export measurement_storage, measurement_units, measurement_metadata
export prepare_wfs_optical_formation, form_wfs_optical_products!
export prepare_wfs_acquisition, acquire_wfs_observation!
export prepare_wfs_estimation, estimate_wfs_measurement!
export AbstractWFSMeasurementPath, AcquiredObservationPath
export DirectMeasurementPath, wfs_measurement_path
export ShackHartmannWFS, PyramidWFS, BioEdgeWFS, ZernikeWFS, CurvatureWFS
export CurvatureReadoutModel, CurvatureCountingReadout, CurvatureBranchResponse
export FluxThresholdValidSubapertures
export CenterOfGravityExtraction, SubapertureLayout, SubapertureCalibration
export subaperture_layout, subaperture_calibration, slope_extraction_model
export valid_subaperture_indices
export MeanValidFluxNormalization, IncidenceFluxNormalization
export measure!, pyramid_modulation_frame!
export valid_subaperture_mask, camera_frame, wfs_detector_image
export shack_hartmann_detector_image, shack_hartmann_detector_image!
export n_valid_subapertures
export LiFT
export LiFTSolveAuto, LiFTSolveQR, LiFTSolveNormalEquations
export LiFTLevenbergMarquardt, LiFTAdaptiveLevenbergMarquardt

export InteractionMatrix, interaction_matrix
export ControlMatrix
export ModalBasis, KLDMModes, KLHHtPSD
export kl_modal_basis, modal_basis, basis_from_m2c
export AOCalibration, ao_calibration, control_matrix
export fitting_error
export GainSensingCamera, calibrate!, compute_optical_gains!

export NullReconstructor, ModalReconstructor, FactorizedReconstructor, MappedReconstructor
export ControlledReconstructor
export reconstruct!, reconstruct
export DiscreteIntegratorController

export AbstractControlSimulation, AbstractExecutionPolicy, SimulationReadout
export AOSimulation, wfs_source, science_source
export SequentialExecution, ThreadedExecution, BackendStreamExecution
export DeterministicExecution, AcceleratedKernelsExecution, DaggerExecution
export ScientificRuntimeProfile, HILRuntimeProfile, RuntimeOutputRequirements, GroupedRuntimeOutputRequirements
export CPUHILExecutionPlan, DeviceResidentExecutionPlan, runtime_execution_plan
export synchronize_runtime!
export OpticalWFSChannel, SharedOpticalArm, SharedOpticalRuntime
export primary_runtime, optical_arms, science_frames, wfs_signals
export VectorDelayLine, shift_delay!
export prepare!, prepare_runtime_wfs!
export command_segments, command_segment_range
export ControlLoopBranch, SingleControlLoopConfig, GroupedControlLoopConfig, ControlLoopScenario
export build_control_loop_scenario, control_loop_name, control_loop_branch_labels
export SimulationEnsemble
export sense!, step!, set_command!
export readout, command, slopes, wfs_frame, science_frame, grouped_wfs_stack
export runtime_timing
export runtime_atmosphere_step

export TomographyAtmosphereParams, LGSAsterismParams, LGSWFSParams
export TomographyParams, TomographyDMParams
export ModelBasedTomography, InteractionMatrixTomography
export SimulationSlopes, InterleavedSlopes, InvertedSlopes
export build_reconstructor, assemble_reconstructor_and_fitting
export zenith_angle_deg, wind_direction_deg
export reconstruct_wavefront_map
export dm_commands
