# Curated public API exported by `using AdaptiveOpticsSim`.
#
# Advanced and developer-facing names remain accessible as
# `AdaptiveOpticsSim.name`. Add names here only when they are part of ordinary
# user workflows, maintained examples, or stable extension seams.

export AdaptiveOpticsSimError, InvalidConfiguration, DimensionMismatchError
export UnsupportedAlgorithm, NumericalConditionError
export AtmosphereTimeError, AtmosphereEpochError
export PlantTimeError, PlantScheduleError
export WFSPreparationError
export PlantDefinitionError, PlantCommandError, PlantPreparationError
export DetectorAcquisitionError

export FidelityProfile, ScientificProfile, FastProfile, default_fidelity_profile
export runtime_rng, deterministic_reference_rng

export InversePolicy, ExactPseudoInverse, TSVDInverse, TikhonovInverse, default_modal_inverse_policy
export CPUBackend, CUDABackend, AMDGPUBackend, MetalBackend
export AbstractArrayBackend, backend

export CircularAperture, AnnularAperture, SpiderMask, RectangularROI, SubapertureGridMask
export build_mask!, apply_mask!

export AbstractAtmosphere
export Telescope, Source, LGSSource, Asterism
export AbstractSourceRadiometry, PhysicalPhotonIrradianceSource
export NormalizedTestSource, source_radiometry, source_radiometric_value
export wavelength, photon_irradiance, optical_path, pupil_photon_rate_map
export reset_opd!, apply_opd!, set_pupil!, set_pupil_reflectivity!
export pupil_mask, pupil_reflectivity, apply_spiders!
export focal_plane_pixel_scale_arcsec

export SpectralSample, SpectralBundle, SpectralSource, with_spectrum
export GaussianDiskSourceModel, PointCloudSourceModel, SampledImageSourceModel
export with_extended_source, extended_source_asterism

export AbstractOpticalProduct, AbstractOpticalPlaneKind
export PupilPlane, FocalPlane, IntermediatePlane, DetectorPlane
export AbstractPlaneCoordinateDomain, MetricCoordinates, AngularCoordinates
export NormalizedPupilCoordinates
export PlaneCentering, SampleCentered, InterSampleCentered
export PlaneAxisOrientation, UnspecifiedSpectralCoordinate
export AchromaticSpectralCoordinate, MonochromaticChannel
export IntegratedSpectralChannel
export AbstractOpticalNormalization, PhotonRateNormalization
export DimensionlessNormalization
export AbstractSpatialMeasure, PointSampledMeasure, SpatialDensityMeasure
export CellIntegratedMeasure
export AbstractCombinationPolicy, CoherentFieldCombination
export IncoherentIntensityAddition, NonCombinableProduct
export UnspecifiedNormalization, UnspecifiedSpatialMeasure, UnspecifiedCoherence
export OpticalPlaneMetadata, plane_metadata, plane_device
export PupilFunction, pupil_support, pupil_amplitude, opd_map
export surface_opd, update_surface!, apply_surface!
export ElectricField, field_values, IntensityMap, intensity_values
export OpticalProductBundle, PreparedIncoherentSum
export prepare_incoherent_sum, accumulate_intensity!
export PupilFieldFormationPlan, prepare_pupil_field
export fill_electric_field!, fill_electric_field_async!
export FraunhoferPropagation, FresnelPropagation
export propagation_output, propagate_field!, fraunhofer_intensity_from_field!
export DirectImagingPlan, DirectImagingWorkspace
export prepare_direct_imaging, form_direct_image!, direct_imaging_output
export direct_imaging_components
export GeometricAtmosphericPropagation, LayeredFresnelAtmosphericPropagation
export AtmosphericFieldPropagation
export propagate_atmosphere_field!, atmospheric_intensity!

export ZernikeBasis, compute_zernike!
export OPDMap, Misregistration, apply_misregistration
export NCPA, KLBasis, ZernikeModalBasis
export SpatialFilter, SpatialFilterWorkspace, SpatialFilterPlan
export CircularFilter, SquareFilter, FoucaultFilter
export prepare_spatial_filter, filter!

export KolmogorovAtmosphere, MultiLayerAtmosphere, InfinitePhaseScreen, InfiniteMultiLayerAtmosphere
export AtmosphereLayerID
export AtmosphereEpoch, epoch_time, epoch_sequence, current_epoch
export prepare_atmosphere_renderer, prepare_atmosphere_renderers, direction_renderers
export advance!, advance_by!, advance_to!, propagate!
export render_atmosphere!

export ActuatorGridTopology, SampledActuatorTopology
export GaussianInfluenceWidth, GaussianMechanicalCoupling, DenseInfluenceMatrix, MeasuredInfluenceFunctions
export ClippedActuators, ActuatorHealthMap, CompositeDMActuatorModel
export DeformableMirror
export influence_model, influence_width
export mechanical_coupling, n_actuators
export FunctionModalBasis, MatrixModalBasis, ZernikeOpticBasis, CartesianTiltBasis
export CompositeControllableOptic, ModalControllableOptic, TipTiltMirror, FocusStage
export update_command!
export DMAdditive, DMReplace

export Detector, APDDetector, LinearAPDDetector, SPADArrayDetector, MKIDArrayDetector
export NoiseModel, NoiseNone, NoisePhoton, NoiseReadout, NoisePhotonReadout
export SensorType, CCDSensor, CMOSSensor, EMCCDSensor, InGaAsSensor
export LinearEMMode, PhotonCountingEMMode, EMOutput, ConventionalOutput, emccd_snr
export SequentialAcquisition, FrameTransferAcquisition
export HgCdTeAvalancheArraySensor, APDSensor, SPADArraySensor, MKIDArraySensor
export SingleElementAPD, APDChannelBank
export FrameResponseModel, NullFrameResponse, GaussianPixelResponse, SampledFrameResponse
export RectangularPixelAperture
export CMOSReadNoiseMap, InterpixelCapacitance, detector_mtf
export PixelResponseNonuniformity, DarkSignalNonuniformity, BadPixelMask, CompositeDetectorDefectModel
export GlobalShutter, RollingShutter, RollingExposure, GlobalResetExposure
export SingleRead, AveragedNonDestructiveReads, CorrelatedDoubleSampling, FowlerSampling
export UpTheRampSampling, SkipperSampling
export FunctionFrameSource, InPlaceFrameSource, FunctionExposureFrameSource, InPlaceExposureFrameSource
export FrameReadoutCorrectionModel, NullFrameReadoutCorrection
export ReferencePixelCommonModeCorrection, ReferenceRowCommonModeCorrection
export ReferenceColumnCommonModeCorrection, ReferenceOutputCommonModeCorrection
export CompositeFrameReadoutCorrection
export FrameReadoutProducts, NoFrameReadoutProducts, MultiReadFrameReadoutProducts
export UpTheRampReadoutProducts, SkipperReadoutProducts, HgCdTeReadoutProducts
export SaturatingFrameNonlinearity, ExponentialPersistence
export AbstractDetectorThermalModel, NullDetectorThermalModel, FixedTemperature, FirstOrderThermalModel
export ArrheniusRateLaw, LinearTemperatureLaw, ExponentialTemperatureLaw
export CountingDeadTimeModel, NoDeadTime, NonParalyzableDeadTime, ParalyzableDeadTime
export DutyCycleGate, AfterpulsingModel, ChannelCrosstalkModel, CompositeCountingCorrelation
export capture!, output_frame, channel_output, detector_export_metadata
export DetectorAcquisitionPlan, prepare_detector_acquisition
export detector_ramp_slope, detector_ramp_intercept
export detector_ramp_cube, detector_ramp_times
export readout_ready, reset_integration!, thermal_model

export Diffractive, Geometric
export WFSObservationMetadata, WFSMeasurementMetadata
export WFSObservation, WFSMeasurement
export observation_storage, observation_units, observation_metadata
export measurement_storage, measurement_units, measurement_metadata
export prepare_wfs_optical_formation, form_wfs_optical_products!
export prepare_wfs_acquisition, acquire_wfs_observation!
export prepare_wfs_estimation, estimate_wfs_measurement!
export AbstractWFSMeasurementPath, AcquiredObservationPath
export DirectMeasurementPath, wfs_measurement_path
export AbstractFocalPlaneModulation, NoModulation, CircularModulation
export SampledModulation
export MicrolensArrayParams, MicrolensArray
export microlens_array, prepare_microlens_propagation
export ShackHartmannDirectFrontEnd, ShackHartmannOpticalFrontEnd
export shack_hartmann_rate_map
export PyramidPhaseMask, PyramidOpticalFrontEnd, pyramid_rate_map
export BioEdgeAmplitudeMask, BioEdgeOpticalFrontEnd, bioedge_rate_map
export set_pyramid_calibration!, set_bioedge_calibration!
export ZernikePhaseSpot, ZernikeOpticalFrontEnd, zernike_rate_map
export CurvatureDefocusPair, CurvatureOpticalFrontEnd, curvature_rate_maps
export CurvaturePackedAcquisition
export set_zernike_calibration!, set_curvature_calibration!
export ShackHartmannWFS, PyramidWFS, BioEdgeWFS, ZernikeWFS, CurvatureWFS
export CurvatureReadoutModel, CurvatureFrameReadout
export CurvatureCountingReadout, CurvatureBranchResponse
export FluxThresholdValidSubapertures
export AbstractSlopeExtractionModel, CenterOfGravityExtraction
export SubapertureLayout, SubapertureCalibration
export subaperture_layout, subaperture_calibration, slope_extraction_model
export set_subaperture_calibration!
export valid_subaperture_indices
export MeanValidFluxNormalization, IncidenceFluxNormalization
export measure!, pyramid_modulation_frame, pyramid_modulation_frame!
export valid_subaperture_mask, camera_frame, wfs_detector_image
export wfs_calibration_signature
export shack_hartmann_detector_image, shack_hartmann_detector_image!
export n_valid_subapertures
export LiFT, PreparedLiFTForwardModel, LiFTObservation
export LiFTIdentityMapping, LiFTFrameMapping
export LiFTPhotonRate, LiFTExpectedCounts, LiFTNormalizedIntensity
export prepare_lift_forward_model, evaluate_lift_forward!
export predict_lift_observation!, lift_forward_output
export lift_observation_contract, diagnostics
export LiFTSolveAuto, LiFTSolveQR, LiFTSolveNormalEquations
export LiFTLevenbergMarquardt, LiFTAdaptiveLevenbergMarquardt

export OpticalPathID, AcquisitionID, ControllableOpticID, CommandEndpointID
export PlantCommandSchemaID, PlantCommandSchemaVersion
export CommandBasisRevision, CommandUnit, CommandSignConvention, CommandBasis
export CommandValueSemantics, AbsoluteCommand, IncrementalCommand
export InvalidCommandAction, RejectInvalidCommand, ClipInvalidCommand
export FailOnInvalidCommand, CommandRangeStage, ValidateOnPresentation
export EnforceOnApplication
export CommandSequenceAction, AcceptSequence, RejectSequence, FailOnSequence
export FutureCommandPolicy, AllowFutureCommand, RejectFutureCommand
export LateCommandPolicy, RejectLateCommand, ApplyLateCommandNow
export FailOnLateCommand
export CommandSupersessionPolicy, PreservePendingCommands
export SupersedeOlderPendingCommands
export CommandSilenceAction, HoldLastCommand, ApplySafeCommand
export FailOnCommandSilence, CommandAgeOrigin, AgeFromAdmission
export AgeFromApplication
export UnboundedCommandValues, UniformCommandBounds
export CommandValuePolicy, CommandSequencePolicy
export CommandEffectiveTimePolicy, CommandSilencePolicy, PlantCommandSchema
export PlantTimestamp, PlantDuration, PeriodicSchedule
export plant_nanoseconds, plant_time_seconds, plant_duration_seconds
export schedule_period, schedule_phase, schedule_timestamp
export RNGDerivationVersion, RNGOwnerIdentity, rng_replay_metadata
export ColdPlantModelDefinition, plant_model_definition_style
export OpticalPathDefinition, AcquisitionDefinition
export ControllableOpticDefinition, PlantDefinition
export path_id, acquisition_id, controllable_optic_id, acquisition_path_id
export path_source, path_model, acquisition_model, controllable_optic_model
export command_schema_id, command_schema_version, command_endpoint_id
export command_numeric_type, command_dimensions, command_units
export command_sign_convention, command_basis, command_basis_revision
export command_semantics, command_bounds, command_value_policy
export command_sequence_policy, command_effective_time_policy
export command_silence_policy, validate_plant_command_payload
export PlantCommandSequence, CommandPresentationID, CommandDispositionReason
export PlantCommand
export CommandSequenceClass, InOrderCommandSequence
export DuplicateCommandSequence, StaleCommandSequence
export ReorderedCommandSequence, SkippedCommandSequence
export CommandAdmissionStatus, CommandAdmittedPending
export CommandAdmittedReady, CommandTerminatedOnAdmission
export CommandTerminalKind, RejectedCommand, SupersededCommand
export AppliedCommand, FailedCommand
export PlantCommandOrderKey, PlantCommandAdmission, PlantCommandDisposition
export PreparedCommandEndpoint, PlantCommandApplicationClaim
export prepare_command_endpoint, validate_plant_command, admit_plant_command!
export command_sequence, command_effective_timestamp, command_payload
export command_presentation_id, command_admission_status
export command_sequence_class, command_order_key
export command_terminal_kind, command_disposition_reason
export command_requested_effective_timestamp, command_terminal_timestamp
export command_admission_timestamp, command_application_timestamp
export command_lateness, superseding_command_presentation_id
export command_endpoint_capacity, command_sequence_window
export command_endpoint_ordinal, pending_command_count, active_command_count
export command_endpoint_timestamp, next_command_order_key
export command_disposition_count, command_disposition
export clear_command_dispositions!, claim_next_application_ready_command!
export claimed_command_payload, mark_plant_command_applied!
export fail_plant_command_application!, fail_pending_plant_commands!
export command_schemas, command_endpoint_ids, command_schema
export plant_command_schema, command_endpoint_owner
export plant_telescope, plant_atmosphere
export controllable_optic_definitions, path_definitions
export acquisition_definitions, controllable_optic_definition
export path_definition, acquisition_definition
export PreparedPlant, prepare_plant
export prepare_pupil_opd_materialization, materialize_path_input!
export execute_path!, execute_acquisition!
export path_result_key, path_input, path_result
export PupilFunctionIlluminationEntry, ElectricFieldIlluminationEntry
export IntensityMapIlluminationEntry, ExternalOpticsResultIlluminationEntry
export DetectorInputIlluminationEntry
export SingleIllumination, ExclusiveIlluminationSelection
export UniformIntensityIllumination, prepare_illumination_entry
export evaluate_illumination!, illumination_entry_boundary
export illumination_evaluator, illumination_destination
export illumination_combination, illumination_visibility
export FullOpticalProviderStyle
export CommandResponsiveReducedOrderProviderStyle
export SyntheticReplayProviderStyle, acquisition_provider_style
export acquisition_provider_payload_work
export prepare_full_optical_provider
export prepare_unchanged_synthetic_provider
export prepare_copied_synthetic_provider, prepare_cyclic_replay_provider
export acquisition_product_contract
export validate_acquisition_product_contract
export acquisition_provider, acquisition_product_metadata
export acquisition_products, acquisition_observation
export acquisition_measurement, prepared_paths, prepared_acquisitions
export prepared_path, prepared_acquisition
export prepare_acquisition_selection
export execute_acquisition_selection!, execute_acquisition_selection_at!

export InteractionMatrix, interaction_matrix
export ControlMatrix
export ModalBasis, KLDMModes, KLHHtPSD
export kl_modal_basis, modal_basis, basis_from_m2c
export AOCalibration, ao_calibration, control_matrix
export fitting_error
export GainSensingCamera, calibrate!, compute_optical_gains!

export NullReconstructor, ModalReconstructor, FactorizedReconstructor, MappedReconstructor
export ControlledReconstructor
export reconstruct!, reconstruct
export DiscreteIntegratorController

export AbstractControlSimulation, AbstractExecutionPolicy, SimulationReadout
export AOSimulation, wfs_source, science_source
export SequentialExecution, ThreadedExecution, BackendStreamExecution
export DeterministicExecution, AcceleratedKernelsExecution, DaggerExecution
export ScientificRuntimeProfile, HILRuntimeProfile, RuntimeOutputRequirements, GroupedRuntimeOutputRequirements
export CPUHILExecutionPlan, DeviceResidentExecutionPlan, runtime_execution_plan
export synchronize_runtime!
export OpticalWFSChannel, SharedOpticalArm, SharedOpticalRuntime
export primary_runtime, optical_arms, science_frames, wfs_signals
export VectorDelayLine, shift_delay!
export prepare!, prepare_runtime_wfs!
export command_segments, command_segment_range
export ControlLoopBranch, SingleControlLoopConfig, GroupedControlLoopConfig, ControlLoopScenario
export build_control_loop_scenario, control_loop_name, control_loop_branch_labels
export SimulationEnsemble
export sense!, step!, set_command!
export readout, command, slopes, wfs_frame, science_frame, grouped_wfs_stack
export runtime_timing
export runtime_atmosphere_step

export TomographyAtmosphereParams, LGSAsterismParams, LGSWFSParams
export TomographyParams, TomographyDMParams
export ModelBasedTomography, InteractionMatrixTomography
export SimulationSlopes, InterleavedSlopes, InvertedSlopes
export build_reconstructor, assemble_reconstructor_and_fitting
export zenith_angle_deg, wind_direction_deg
export reconstruct_wavefront_map
export dm_commands
