# Curated package API.
#
# Export only names used routinely after `using AdaptiveOpticsSim`. Declare
# stable advanced and developer-facing seams `public` so callers can use
# `AdaptiveOpticsSim.name` or import them explicitly without adding them to the
# ordinary user namespace.

export AdaptiveOpticsSimError, InvalidConfiguration, DimensionMismatchError
export UnsupportedAlgorithm, NumericalConditionError
export AtmosphereTimeError, AtmosphereEpochError
export WFSPreparationError
export Backends, Optics, Plant

export FidelityProfile, ScientificProfile, FastProfile, default_fidelity_profile
export runtime_rng, deterministic_reference_rng

export InversePolicy, ExactPseudoInverse, TSVDInverse, TikhonovInverse, default_modal_inverse_policy
export AbstractAtmosphere
export GeometricAtmosphericPropagation, LayeredFresnelAtmosphericPropagation
export AtmosphericFieldPropagation
export propagate_atmosphere_field!, atmospheric_intensity!

export KLBasis, ZernikeModalBasis

export KolmogorovAtmosphere, MultiLayerAtmosphere, InfinitePhaseScreen, InfiniteMultiLayerAtmosphere
export AtmosphereLayerID
export AtmosphereEpoch, epoch_time, epoch_sequence, current_epoch
export prepare_atmosphere_renderer, prepare_atmosphere_renderers, direction_renderers
export prepare_atmosphere_direction_batch, render_atmosphere_directions!
export atmosphere_direction_output
public AbstractAtmosphereDirectionBatchCapability
public ExtractedScreenDirectionBatchCapability
public UnsupportedAtmosphereDirectionBatchCapability
public AtmosphereDirectionBatchParams, AtmosphereDirectionBatchWorkspace
public PreparedAtmosphereDirectionBatch
public atmosphere_direction_batch_capability
public atmosphere_direction_count, atmosphere_direction_capacity
public atmosphere_direction_metadata, validate_atmosphere_direction_batch
export advance!, advance_by!, advance_to!, propagate!
export render_atmosphere!

export Detector, APDDetector, LinearAPDDetector, SPADArrayDetector, MKIDArrayDetector
export NoiseModel, NoiseNone, NoisePhoton, NoiseReadout, NoisePhotonReadout
export SensorType, CCDSensor, CMOSSensor, EMCCDSensor, InGaAsSensor
export LinearEMMode, PhotonCountingEMMode, EMOutput, ConventionalOutput, emccd_snr
export SequentialAcquisition, FrameTransferAcquisition
export HgCdTeAvalancheArraySensor, APDSensor, SPADArraySensor, MKIDArraySensor
export SingleElementAPD, APDChannelBank
export FrameResponseModel, NullFrameResponse, GaussianPixelResponse, SampledFrameResponse
export RectangularPixelAperture
export CMOSReadNoiseMap, InterpixelCapacitance, detector_mtf
export PixelResponseNonuniformity, DarkSignalNonuniformity, BadPixelMask, CompositeDetectorDefectModel
export GlobalShutter, RollingShutter, RollingExposure, GlobalResetExposure
export SingleRead, AveragedNonDestructiveReads, CorrelatedDoubleSampling, FowlerSampling
export UpTheRampSampling, SkipperSampling
export FunctionFrameSource, InPlaceFrameSource, FunctionExposureFrameSource, InPlaceExposureFrameSource
export FrameReadoutCorrectionModel, NullFrameReadoutCorrection
export ReferencePixelCommonModeCorrection, ReferenceRowCommonModeCorrection
export ReferenceColumnCommonModeCorrection, ReferenceOutputCommonModeCorrection
export CompositeFrameReadoutCorrection
export FrameReadoutProducts, NoFrameReadoutProducts, MultiReadFrameReadoutProducts
export UpTheRampReadoutProducts, SkipperReadoutProducts, HgCdTeReadoutProducts
export SaturatingFrameNonlinearity, ExponentialPersistence
export AbstractDetectorThermalModel, NullDetectorThermalModel, FixedTemperature, FirstOrderThermalModel
export ArrheniusRateLaw, LinearTemperatureLaw, ExponentialTemperatureLaw
export CountingDeadTimeModel, NoDeadTime, NonParalyzableDeadTime, ParalyzableDeadTime
export DutyCycleGate, AfterpulsingModel, ChannelCrosstalkModel, CompositeCountingCorrelation
export capture!, output_frame, channel_output, detector_export_metadata
export DetectorAcquisitionPlan, prepare_detector_acquisition
export detector_ramp_slope, detector_ramp_intercept
export detector_ramp_cube, detector_ramp_times
export readout_ready, reset_integration!, thermal_model

export Diffractive, Geometric
export WFSObservationMetadata, WFSMeasurementMetadata
export WFSObservation, WFSMeasurement
export observation_storage, observation_units, observation_metadata
export measurement_storage, measurement_units, measurement_metadata
export prepare_wfs_optical_formation, form_wfs_optical_products!
export prepare_wfs_acquisition, acquire_wfs_observation!
export prepare_wfs_estimation, estimate_wfs_measurement!
export AbstractWFSMeasurementPath, AcquiredObservationPath
export DirectMeasurementPath, wfs_measurement_path
export ShackHartmannDirectFrontEnd, ShackHartmannOpticalFrontEnd
export shack_hartmann_rate_map
export PyramidOpticalFrontEnd, pyramid_rate_map
export BioEdgeOpticalFrontEnd, bioedge_rate_map
export set_pyramid_calibration!, set_bioedge_calibration!
export ZernikeOpticalFrontEnd, zernike_rate_map
export CurvatureOpticalFrontEnd, curvature_rate_maps
export CurvaturePackedAcquisition
export set_zernike_calibration!, set_curvature_calibration!
export ShackHartmannWFS, PyramidWFS, BioEdgeWFS, ZernikeWFS, CurvatureWFS
export CurvatureReadoutModel, CurvatureFrameReadout
export CurvatureCountingReadout, CurvatureBranchResponse
export FluxThresholdValidSubapertures
export AbstractSlopeExtractionModel, CenterOfGravityExtraction
export SubapertureLayout, SubapertureCalibration
export subaperture_layout, subaperture_calibration, slope_extraction_model
export set_subaperture_calibration!
export valid_subaperture_indices
export MeanValidFluxNormalization, IncidenceFluxNormalization
export measure!, pyramid_modulation_frame, pyramid_modulation_frame!
export valid_subaperture_mask, camera_frame, wfs_detector_image
export slopes, wfs_calibration_signature
export prepare_runtime_wfs!
export shack_hartmann_detector_image, shack_hartmann_detector_image!
export n_valid_subapertures
export LiFT, PreparedLiFTForwardModel, LiFTObservation
export LiFTIdentityMapping, LiFTFrameMapping
export LiFTPhotonRate, LiFTExpectedCounts, LiFTNormalizedIntensity
export prepare_lift_forward_model, evaluate_lift_forward!
export predict_lift_observation!, lift_forward_output
export lift_observation_contract, diagnostics
export LiFTSolveAuto, LiFTSolveQR, LiFTSolveNormalEquations
export LiFTLevenbergMarquardt, LiFTAdaptiveLevenbergMarquardt

export InteractionMatrix, interaction_matrix
export ControlMatrix
export ModalBasis, KLDMModes, KLHHtPSD
export kl_modal_basis, modal_basis, basis_from_m2c
export AOCalibration, ao_calibration, control_matrix
export fitting_error
export GainSensingCamera, calibrate!, compute_optical_gains!

export NullReconstructor, ModalReconstructor, FactorizedReconstructor, MappedReconstructor
export ControlledReconstructor
export reconstruct!, reconstruct
export DiscreteIntegratorController, VectorDelayLine, shift_delay!

export AbstractExecutionPolicy
export SequentialExecution, ThreadedExecution, BackendStreamExecution
export DeterministicExecution, AcceleratedKernelsExecution, DaggerExecution
export SimulationEnsemble
export runtime_timing

public controller_output, reset_controller!, supports_controller_reset
public run_ensemble!, ensemble_members, execution_policy
public ensemble_ownership_roots, init_ensemble_scheduler, execute_ensemble!
public supports_prepared_runtime, supports_detector_output
public supports_stacked_sources, supports_grouped_execution
public init_execution_state

export TomographyAtmosphereParams, LGSAsterismParams, LGSWFSParams
export TomographyParams, TomographyDMParams
export ModelBasedTomography, InteractionMatrixTomography
export SimulationSlopes, InterleavedSlopes, InvertedSlopes
export build_reconstructor, assemble_reconstructor_and_fitting
export zenith_angle_deg, wind_direction_deg
export reconstruct_wavefront_map
export dm_commands
